---
title: "Association between Community Mobility and New COVID-19 Cases in Texas"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Importing in Datasets and cutting to date range and State
library(readr)
X2020_US_Region_Mobility_Report_Nov6 <- read_csv("2020_US_Region_Mobility_Report_Nov6.csv")
United_States_COVID_19_Cases_and_Deaths_by_State_over_Time <- read_csv("United_States_COVID-19_Cases_and_Deaths_by_State_over_Time.csv")
##Cutting of mobility data
USmobilityReport=X2020_US_Region_Mobility_Report_Nov6
TexasMobilityReport=subset(USmobilityReport, USmobilityReport$iso_3166_2_code=="US-TX")
TexasMobilityReport=subset(TexasMobilityReport, TexasMobilityReport$date<'2020-11-01')
##Cutting of COVID data
US_Covid_data<-United_States_COVID_19_Cases_and_Deaths_by_State_over_Time
TX_Covid_data<-subset(US_Covid_data, US_Covid_data$state=="TX")
TX_Covid_data$submission_date<- as.Date(TX_Covid_data$submission_date, format = "%m/%d/%y")
##Mergigng datasets
Texas_COVID_Mobility<-merge(TexasMobilityReport, TX_Covid_data, by.x='date', by.y='submission_date')
Texas_COVID_Mobility<-subset(Texas_COVID_Mobility,select=-c(country_region_code,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,conf_cases,prob_cases,pnew_case,conf_death,prob_death,pnew_death,created_at,consent_cases,consent_deaths))

#Viewing Variables over time
#New Cases over time
plot(Texas_COVID_Mobility$date,Texas_COVID_Mobility$new_case,ylim=range(Texas_COVID_Mobility$new_case), xlim=range(Texas_COVID_Mobility$date), type="l", col="green", lwd=2, xlab="Date", ylab="New Cases")
title("New Cases Over Time")

plot(Texas_COVID_Mobility$date,Texas_COVID_Mobility$retail_and_recreation_percent_change_from_baseline,ylim=range(Texas_COVID_Mobility$parks_percent_change_from_baseline), xlim=range(Texas_COVID_Mobility$date), type="l", col="green", lwd=2, xlab="Date", ylab="Percent Change From Baseline")
lines(Texas_COVID_Mobility$date, Texas_COVID_Mobility$grocery_and_pharmacy_percent_change_from_baseline, col="red", lwd=2)
lines(Texas_COVID_Mobility$date, Texas_COVID_Mobility$parks_percent_change_from_baseline, col="blue", lwd=2)
lines(Texas_COVID_Mobility$date, Texas_COVID_Mobility$transit_stations_percent_change_from_baseline, col="orange", lwd=2)
lines(Texas_COVID_Mobility$date, Texas_COVID_Mobility$workplaces_percent_change_from_baseline, col="purple", lwd=2)
lines(Texas_COVID_Mobility$date, Texas_COVID_Mobility$residential_percent_change_from_baseline, col="black", lwd=2)
title("Percent Change From Baseline Over Time")

#Data manipulation for rolling averages
library(dplyr)
library(zoo)

Texas_COVID_Mobility_Rolling<- Texas_COVID_Mobility %>%
  dplyr::mutate(newCase_07da = zoo::rollmean(new_case, k = 7, fill = NA),
                retail_and_recreation_percent_change_from_baseline_07da = zoo::rollmean(retail_and_recreation_percent_change_from_baseline, k = 7, fill = NA),
                grocery_and_pharmacy_percent_change_from_baseline_07da = zoo::rollmean(grocery_and_pharmacy_percent_change_from_baseline, k = 7, fill = NA),
                parks_percent_change_from_baseline_07da = zoo::rollmean(parks_percent_change_from_baseline, k = 7, fill = NA),
                transit_stations_percent_change_from_baseline_07da = zoo::rollmean(transit_stations_percent_change_from_baseline, k = 7, fill = NA),
                workplaces_percent_change_from_baseline_07da = zoo::rollmean(workplaces_percent_change_from_baseline, k = 7, fill = NA),
                residential_percent_change_from_baseline_07da = zoo::rollmean(residential_percent_change_from_baseline, k = 7, fill = NA)) 

Texas_COVID_Mobility_Rolling <- na.omit(Texas_COVID_Mobility_Rolling) 

#Vieweing Variables Over time for Rolling Data

#7-day Rolling Average of New Cases over time
plot(Texas_COVID_Mobility_Rolling$date,Texas_COVID_Mobility_Rolling$newCase_07da,ylim=range(Texas_COVID_Mobility_Rolling$newCase_07da), xlim=range(Texas_COVID_Mobility_Rolling$date), type="l", col="green", lwd=2, xlab="Date", ylab="7-day Rolling Average of New Cases")
title("7-day Rolling Average of New Cases Over Time")

#7-day Rolling Average of Percent Change from Baseline Overtime
plot(Texas_COVID_Mobility_Rolling$date,Texas_COVID_Mobility_Rolling$retail_and_recreation_percent_change_from_baseline_07da,ylim=range(c(Texas_COVID_Mobility_Rolling$parks_percent_change_from_baseline_07da,Texas_COVID_Mobility_Rolling$workplaces_percent_change_from_baseline_07da)), xlim=range(Texas_COVID_Mobility_Rolling$date), type="l", col="green", lwd=2, xlab="Date", ylab="7-Day rolling average of Percent Change From Baseline")
lines(Texas_COVID_Mobility_Rolling$date,Texas_COVID_Mobility_Rolling$grocery_and_pharmacy_percent_change_from_baseline_07da, col="red", lwd=2)
lines(Texas_COVID_Mobility_Rolling$date, Texas_COVID_Mobility_Rolling$parks_percent_change_from_baseline_07da, col="blue", lwd=2)
lines(Texas_COVID_Mobility_Rolling$date,Texas_COVID_Mobility_Rolling$transit_stations_percent_change_from_baseline_07da, col="orange", lwd=2)
lines(Texas_COVID_Mobility_Rolling$date,Texas_COVID_Mobility_Rolling$workplaces_percent_change_from_baseline_07da, col="purple", lwd=2)
lines(Texas_COVID_Mobility_Rolling$date,Texas_COVID_Mobility_Rolling$residential_percent_change_from_baseline_07da, col="black", lwd=2)
title("7-day Rolling Average of Percent Change From Baseline Over Time")

#Removing unused variables and omitting na's
Texas_COVID_Mobility=subset(Texas_COVID_Mobility[,-c(1,2,9,10,12,13)])
Texas_COVID_Mobility_Rolling=subset(Texas_COVID_Mobility_Rolling[,-c(1:13)])
Texas_COVID_Mobility_Rolling <- na.omit(Texas_COVID_Mobility_Rolling) 
```



```{r}
#looking at data
#Original
library(ISLR)
summary(Texas_COVID_Mobility)
pairs(Texas_COVID_Mobility)
cor(Texas_COVID_Mobility)
plot(Texas_COVID_Mobility$retail_and_recreation_percent_change_from_baseline, Texas_COVID_Mobility$new_case)
plot(Texas_COVID_Mobility$grocery_and_pharmacy_percent_change_from_baseline, Texas_COVID_Mobility$new_case)
plot(Texas_COVID_Mobility$parks_percent_change_from_baseline, Texas_COVID_Mobility$new_case)
plot(Texas_COVID_Mobility$transit_stations_percent_change_from_baseline, Texas_COVID_Mobility$new_case)
plot(Texas_COVID_Mobility$workplaces_percent_change_from_baseline, Texas_COVID_Mobility$new_case)
plot(Texas_COVID_Mobility$residential_percent_change_from_baseline, Texas_COVID_Mobility$new_case)

```


```{r}
#Rolling
summary(Texas_COVID_Mobility_Rolling)
pairs(Texas_COVID_Mobility_Rolling)
cor(Texas_COVID_Mobility_Rolling)
plot(Texas_COVID_Mobility_Rolling$retail_and_recreation_percent_change_from_baseline_07da, Texas_COVID_Mobility_Rolling$newCase_07da)
plot(Texas_COVID_Mobility_Rolling$grocery_and_pharmacy_percent_change_from_baseline_07da, Texas_COVID_Mobility_Rolling$newCase_07da)
plot(Texas_COVID_Mobility_Rolling$parks_percent_change_from_baseline_07da, Texas_COVID_Mobility_Rolling$newCase_07da)
plot(Texas_COVID_Mobility_Rolling$transit_stations_percent_change_from_baseline_07da, Texas_COVID_Mobility_Rolling$newCase_07da)
plot(Texas_COVID_Mobility_Rolling$workplaces_percent_change_from_baseline_07da, Texas_COVID_Mobility_Rolling$newCase_07da)
plot(Texas_COVID_Mobility_Rolling$residential_percent_change_from_baseline_07da, Texas_COVID_Mobility_Rolling$newCase_07da)

```


```{r}
#testing a linear model on Rolling Data
lm.fit=lm(newCase_07da~ retail_and_recreation_percent_change_from_baseline_07da+
                        grocery_and_pharmacy_percent_change_from_baseline_07da+
                        parks_percent_change_from_baseline_07da+
                        transit_stations_percent_change_from_baseline_07da+
                        workplaces_percent_change_from_baseline_07da+
                        residential_percent_change_from_baseline_07da, data = Texas_COVID_Mobility_Rolling)
summary(lm.fit)
par(mfrow =c(2,2))
plot(lm.fit)


```

```{r}
#Applying 7 Day lag and standardizing  Dataset 
#Applying 7 Day lag to Dataset
do_lag <- function(the_data, variables, num_periods) {
  num_vars <- length(variables)
  num_rows <- nrow(the_data)
  
  for (j in 1:num_vars) {
    for (i in 1:num_periods) {
      the_data[[paste0(variables[j], i)]] <- c(rep(NA, i), head(the_data[[variables[j]]], num_rows - i))
    }
  }
  
  return(the_data)
}
n=7
variables<-c('retail_and_recreation_percent_change_from_baseline_07da','grocery_and_pharmacy_percent_change_from_baseline_07da','parks_percent_change_from_baseline_07da','transit_stations_percent_change_from_baseline_07da','workplaces_percent_change_from_baseline_07da','residential_percent_change_from_baseline_07da')
Texas_COVID_Mobility_Rolling_lag<-do_lag(Texas_COVID_Mobility_Rolling, variables, n) 
# Texas_COVID_Mobility_Rolling_lag<-lag(Texas_COVID_Mobility_Rolling[,-1], n = 7)
# Texas_COVID_Mobility_Rolling_lag$newCase_07da<-Texas_COVID_Mobility_Rolling$newCase_07da
# Texas_COVID_Mobility_Rolling_lag_noNA<-Texas_COVID_Mobility_Rolling_lag[-c(1:7),]

#Standardizing variables
vars<-ls(Texas_COVID_Mobility_Rolling_lag[,-1])
Texas_COVID_Mobility_Rolling_lag_Standardized <- Texas_COVID_Mobility_Rolling_lag %>% mutate_at(vars, ~(scale(.) %>% as.vector))
Texas_COVID_Mobility_Rolling_lag_Standardized=na.omit(Texas_COVID_Mobility_Rolling_lag_Standardized)

```


```{r}
#Applying Elastic Net
#Creating Split
library(tidyverse)
library(caret)
library(glmnet)
set.seed(123)
training.samples <- Texas_COVID_Mobility_Rolling_lag_Standardized$newCase_07da %>%
  createDataPartition(p = 0.7, list = FALSE)
train.data  <- Texas_COVID_Mobility_Rolling_lag_Standardized[training.samples, ]
test.data <- Texas_COVID_Mobility_Rolling_lag_Standardized[-training.samples, ]

#Predictor and outcome variables
x <- model.matrix(newCase_07da~., train.data)[,-1]
y <- train.data$newCase_07da

```


```{r}
#Ridge
set.seed(123) 
cv <- cv.glmnet(x, y, alpha = 0)
cv$lambda.min
ridge <- glmnet(x, y, alpha = 0, lambda = cv$lambda.min)
coef(ridge)
# Make predictions on the test data
x.test <- model.matrix(newCase_07da ~., test.data)[,-1]
predictions <- ridge %>% predict(x.test) %>% as.vector()
# Model performance metrics
data.frame(
  RMSE = RMSE(predictions, test.data$newCase_07da),
  Rsquare = R2(predictions, test.data$newCase_07da)
)
```


```{r}
#Lasso
# Find the best lambda using cross-validation
set.seed(123) 
cv <- cv.glmnet(x, y, alpha = 1)
# Display the best lambda value
cv$lambda.min
# Fit the final model on the training data
lasso <- glmnet(x, y, alpha = 1, lambda = cv$lambda.min)
# regression coefficients
coef(lasso)
# Make predictions on the test data
x.test <- model.matrix(newCase_07da ~., test.data)[,-1]
predictions <- lasso %>% predict(x.test) %>% as.vector()
# Model performance metrics
data.frame(
  RMSE = RMSE(predictions, test.data$newCase_07da),
  Rsquare = R2(predictions, test.data$newCase_07da)
)

```


```{r}
#Determining best tuning parameter
set.seed(123)
elastic <- train(
  newCase_07da ~., data = train.data, method = "glmnet",
  trControl = trainControl("cv", number = 10),
  tuneLength = 10
)
elastic$bestTune

#Coefficients of model
coef(elastic$finalModel, elastic$bestTune$lambda)

#Applying to test data
# Make predictions on the test data
x.test <- model.matrix(newCase_07da ~., test.data)[,-1]
predictions <- elastic %>% predict(x.test)

# Model performance metrics
data.frame(
  RMSE = RMSE(predictions, test.data$newCase_07da),
  Rsquare = R2(predictions, test.data$newCase_07da)
)
```

```{r}
#Plots
lambdas_to_try <- 10^seq(-3, 5, length.out = 100)
elastic_cv <- cv.glmnet(x, y, alpha = 0.9, lambda = lambdas_to_try,
                      standardize = TRUE, nfolds = 10)
plot(elastic_cv,main="elastic")

res <- glmnet(x, y, alpha = 0.9, lambda = lambdas_to_try, standardize = FALSE)
plot(res, xvar = "lambda")
#legend("bottomright", lwd = 1, col = 1:6, legend = colnames(x), cex = .7)
#Plots
lambdas_to_try <- 10^seq(-3, 5, length.out = 100)
lasso_cv <- cv.glmnet(x, y, alpha = 1, lambda = lambdas_to_try,
                      standardize = TRUE, nfolds = 10)
plot(lasso_cv,main="lasso")

res <- glmnet(x, y, alpha = 1, lambda = lambdas_to_try, standardize = FALSE)
plot(res, xvar = "lambda")
#legend("bottomright", lwd = 1, col = 1:6, legend = colnames(x), cex = .7)
#Plots
lambdas_to_try <- 10^seq(-3, 5, length.out = 100)
ridge_cv <- cv.glmnet(x, y, alpha = 0, lambda = lambdas_to_try,
                      standardize = TRUE, nfolds = 10)
plot(ridge_cv,main="ridge")

res <- glmnet(x, y, alpha = 0, lambda = lambdas_to_try, standardize = FALSE)
plot(res, xvar = "lambda")
#legend("bottomright", lwd = 1, col = 1:6, legend = colnames(x), cex = .7)
```


```{r}
#testing a linear model on Rolling Data lagged data
lm.fit=lm(newCase_07da~., data = Texas_COVID_Mobility_Rolling_lag_Standardized)
summary(lm.fit)
par(mfrow =c(2,2))
plot(lm.fit)
```

```{r}
#Plotting the influential variables and magnitudes
library(tidyverse)
library(broom)

coef(elastic$finalModel, s = elastic$bestTune$lambda) %>%
  tidy() %>%
  filter(row != "(Intercept)") %>%
  ggplot(aes(value, reorder(row, value), color = value > 0)) +
  geom_point(show.legend = FALSE) +
  xlab("Coefficient Value") +
  ylab("Selected Mobility Variables")
```

```{r}
#Adding the coefficients given by elastic net pertaining to Days 1-7 to a matrix (plot_matrix)
c_tmp <- coef(elastic$finalModel, s = elastic$bestTune$lambda)
plot_matrix <- matrix(data = 0, nrow = 6, ncol = 7) 
counter1 <- 1
counter2 <- 1
for(var in 1:length(c_tmp)){
  if(var > 7){
    plot_matrix[counter1, counter2] <- c_tmp[var, 1]
    if(counter2 %% 7 == 0){
      counter2 <- 1
      counter1 <- counter1 + 1
    }
    else{
      counter2 <- counter2 + 1
    }
  }
}

#Adding the coefficients given by elastic net pertaining to Day 0 to the matrix (plot_matrix)
col_tmp <- c()
for(var in 2:7){
  col_tmp <- c(col_tmp, c_tmp[var, 1]) 
}
plot_matrix <- cbind(col_tmp, plot_matrix)
colnames(plot_matrix) <- NULL

#Plotting the 7-day lag analysis
my_colors <- c("blue", "red", "green", "purple", "orange", "yellow")
x_vals <- c(0,1:7)
for(var1 in 1:6){
  if(var1 == 1){
    plot(x_vals, plot_matrix[var1,], type="o", col="blue", pch=20, lty=1, ylab = "Coefficient Value", xlab = "7-Day Lag",ylim=c(-3000,2500))
  }
  else{
    points(x_vals, plot_matrix[var1,], col=my_colors[var1],pch=20)
    lines(x_vals, plot_matrix[var1,], col=my_colors[var1], lty=1)
  }
}
legend(1.8,-1100,legend=c("Recreation","Grocery","Parks","Transit","Workplaces","Residential"), col=my_colors,pch=20,lty=1, ncol=2)
```

```{r}
#Determining that with the lowest RSS
library(leaps)
models = regsubsets(newCase_07da ~ ., data = train.data, nvmax = length(train.data[,-1]))
```


```{r}
#Plotting the output of adjusted R squared, Bayesian Information Criterion (BIC), and Cp, respectively, from that giving the lowest RSS
models_results <- summary(models)
plotting_function = function(results) {
  tibble(predictors = 1:48,
  adj_R2 = results$adjr2,
  Cp = results$cp,
  BIC = results$bic) %>%
  gather(statistic, value, -predictors) %>%
  ggplot(aes(predictors, value, color = statistic)) +
  geom_line(show.legend = F) +
  geom_point(show.legend = F) +
  facet_wrap(~ statistic, scales = "free")
}
plotting_function(models_results)
```

```{r}
#The best first determined by adjusted R squared out of that with the smallest RSS
preds <- output_predictors_2(which.max(models_results$adjr2))
tmp_formula <- as.formula(paste0("newCase_07da ~ ", paste(preds, collapse = " + ")))
tmp_adjr2 = lm(tmp_formula, train.data)

#The best first determined by Bayesian Information Criterion (BIC) out of that with the smallest RSS
preds <- output_predictors_2(which.min(models_results$bic))
tmp_formula <- as.formula(paste0("newCase_07da ~ ", paste(preds, collapse = " + ")))
tmp_bic = lm(tmp_formula, train.data)

#The best first determined by Cp out of that with the smallest RSS
preds <- output_predictors_2(which.min(models_results$cp))
tmp_formula <- as.formula(paste0("newCase_07da ~ ", paste(preds, collapse = " + ")))
tmp_cp = lm(tmp_formula, train.data)

x.train.data <- train.data[, -train.data[, "newCase_07da"]]
y.train.data <- train.data[, "newCase_07da"]
x <- model.matrix(newCase_07da~., train.data)[,-1]
y <- train.data$newCase_07da

#Plotting a model utilizing all mobility variables
tmp_all_mobility <- lm(newCase_07da~., train.data)

#Creating the elastic net visualization and comparison plot
plot(y, ylab = "Response", xlab = "Mobility Input",ylim=c(-2000,10000))
lines(tmp_all_mobility$fitted.values, col = "purple")
lines(tmp_adjr2$fitted.values, col = "yellow")
lines(tmp_bic$fitted.values, col = "green")
lines(tmp_cp$fitted.values, col = "red")
x5 <- model.matrix(newCase_07da~., train.data)[,-1]
y5 <- train.data$newCase_07da
enet <- glmnet(x5, y5, family = "gaussian", alpha = 0.7, lambda = 10.35226)
enet.y <- predict(enet, newx = x5, type = "response", s=10.35226)
lines(enet.y, lty=1, lwd=1.7,col="black")
```

